### ISSUE TITLE
Reunion Venue: Available dates and prices

### ISSUE THREAD

**Issue by cyndiclamp** [edreamleo/NTHS-Reunion#18]
Here are the ticket prices and available dates for three available venues. 

**Renaissance Chicago North Shore**  
Available September 16, ~~September 30~~ (conflicts with Yom Kippur) and October 7, 2017
Ticket Price: $121 per person, Plated Chicken Dinner and Cash Bar
Ticket Price: $125 per person, Buffet Dinner and Cash Bar

**DoubleTree Hotel Skokie**
Available September 16, October 7 and October 14, 2017
Ticket Price: $125 per person, Hors d'oeuvres, Plated Chicken or Beef or Buffet Dinner, and Cash Bar

Room rates: $139 including breakfast, or $129 without breakfast.

The DoubleTree Hotel has a sound system we may use with an iPod instead of a DJ.  This would reduce the cost by $2 per person.  The DoubleTree has also offered one complimentary guest room.

**Hilton Garden Inn in Evanston**
Room rates are $169 to $189 per night.
Ticket price: $105/person.
Dates: September 2, Sept. 9, Oct. 14.

**Hilton Orrington in Evanston**
The Hilton Orrington has a $18,000 minimum, which would be very hard for your class to meet, making it not a good fit for your reunion.

**Notes**

1. Jewish Holidays are Yom Kippur:  Sept 30, and Rosh Hashanah Sept. 20.

2. (Cyndi) The per person prices listed below include the food and beverage options shown and our complete reunion coordination services, including:

• all upfront costs and deposits, and the signing of all contracts and agreements 
• color printing, postage and assembly of the save the date and reunion invitation mailing
• nametags with classmate high school photos, and guest nametags
• DJ Entertainment
• reunion night staffing so you may enjoy the party as a guest
• updated alumni directory for each classmate attending
• acceptance of credit card payments
• search to find classmates, and database management of the class list

**Comment by edreamleo** [comment]
I think it's important to pick a venue and date soon.

My preference would be the Renaissance Chicago North Shore, because it's closer to the North Shore, and because there have been other New Trier reunions there.

**Comment by edreamleo** [comment]
I am going to close this item.  The decision has been made.
