### ISSUE TITLE
Task: pick a venue

### ISSUE THREAD

**Issue by edreamleo** [edreamleo/NTHS-Reunion#9]
There are now at least three possible venues:
1. The [Renaissance Hotel](http://www.marriott.com/hotels/travel/chinb-renaissance-chicago-north-shore-hotel/) in Northbrook.
2. The [Chicago Athletic Hotel](http://www.chicagoathletichotel.com/) in downtown Chicago, directly across from Millennium Park. Deb's son is currently the manager at this hotel.
3. The [Orrington Hotel](http://www.hotelsone.com/evanston-hotels-us/hilton-orrington-evanston.html) in Evanston.

Cyndi will be investigating rates for reserved blocks at each location.  That will be one starting point for our consideration.  Location will surely be another.

**Comment by jpdobson** [comment]
I think this sounds like a really great and fun idea.

**Comment by edreamleo** [comment]
Closed.  This is a duplicate.
